version: '3'

services: 
  blog-client: 
    build: ./nanlan-blog-client
    depends_on: 
      - blog-server
      - mongodb
    volumes:
      - "/nanlan-blog/log:/var/log/nginx"
    network_mode: "service:mongodb"
  blog-server:
    build: ./nanlan-blog-server
    depends_on: 
      - mongodb
    network_mode: "service:mongodb"
  mongodb:
    image: mongo
    volumes:
      - "/nanlan-blog/db:/data/db"
    ports: 
      - "8080:80"
      - "3000:3000"
      - "27017:27017"
    